/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import main.dbconnect;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Global
 */
public class flightHandler extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form flightHandler
     */
    public flightHandler() {
        initComponents();
        
        //set the location of the jframe to the center of the screen
        this.pack();
        this.setLocationRelativeTo(null);
        
        //connecting to DB
        con = dbconnect.connect();
        
        //load table
        tableLoad3(1);
        
    }
    
    private void tableLoad3(int a){
        try{
            String q2 = "SELECT * FROM flight";
            pst = con.prepareStatement(q2);
            rs = pst.executeQuery();
            
            if(a==1){
                flightAddTable.setModel(DbUtils.resultSetToTableModel(rs));
            }else if(a==2){
                flightEditDeleteTable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            
        }catch(SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinField1 = new com.toedter.components.JSpinField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        addFlight = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        fname = new javax.swing.JTextField();
        destination = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        departTime = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        flightAddTable = new javax.swing.JTable();
        origin = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        returnTime = new javax.swing.JTextField();
        no = new javax.swing.JLabel();
        yes = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        nos = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        returnTime2 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        editRemoveFlight = new javax.swing.JPanel();
        date1 = new com.toedter.calendar.JDateChooser();
        jSeparator5 = new javax.swing.JSeparator();
        destination1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        departTime1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        flightEditDeleteTable = new javax.swing.JTable();
        origin1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        nos1 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        returnTime3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        price1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        returnTime1 = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        fnameLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Add_32.png")); // NOI18N
        jButton1.setAutoscrolls(true);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Edit_32.png")); // NOI18N
        jButton2.setAutoscrolls(true);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Logout_Rounded_Left_32.png")); // NOI18N
        jButton8.setAutoscrolls(true);
        jButton8.setBorderPainted(false);
        jButton8.setDefaultCapable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        main.setLayout(new java.awt.CardLayout());

        addFlight.setBackground(new java.awt.Color(36, 47, 65));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add a new Flight");

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Origin");

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Destination");

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("DepartTime");

        fname.setBackground(new java.awt.Color(36, 47, 65));
        fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setBorder(null);
        fname.setCaretColor(new java.awt.Color(255, 255, 255));
        fname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fnameCaretUpdate(evt);
            }
        });

        destination.setBackground(new java.awt.Color(36, 47, 65));
        destination.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destination.setForeground(new java.awt.Color(255, 255, 255));
        destination.setBorder(null);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Airport_104px.png")); // NOI18N

        departTime.setBackground(new java.awt.Color(36, 47, 65));
        departTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departTime.setForeground(new java.awt.Color(255, 255, 255));
        departTime.setBorder(null);

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));

        flightAddTable.setBackground(new java.awt.Color(204, 204, 204));
        flightAddTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Food", "Drink", "Cabin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(flightAddTable);

        origin.setBackground(new java.awt.Color(36, 47, 65));
        origin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        origin.setForeground(new java.awt.Color(255, 255, 255));
        origin.setBorder(null);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Enter_32.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Flight Name");

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Return Time");

        returnTime.setBackground(new java.awt.Color(36, 47, 65));
        returnTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        returnTime.setForeground(new java.awt.Color(255, 255, 255));
        returnTime.setBorder(null);

        no.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Cancelcolor_32.png")); // NOI18N

        yes.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Ok_32.png")); // NOI18N

        date.setDateFormatString("yyyy-MM-dd");

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Enter Your Username");

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("No of seats");

        nos.setBackground(new java.awt.Color(36, 47, 65));
        nos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nos.setForeground(new java.awt.Color(255, 255, 255));
        nos.setBorder(null);

        returnTime2.setBackground(new java.awt.Color(36, 47, 65));
        returnTime2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        returnTime2.setForeground(new java.awt.Color(255, 255, 255));
        returnTime2.setBorder(null);

        jLabel20.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Price");

        price.setBackground(new java.awt.Color(36, 47, 65));
        price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setBorder(null);

        javax.swing.GroupLayout addFlightLayout = new javax.swing.GroupLayout(addFlight);
        addFlight.setLayout(addFlightLayout);
        addFlightLayout.setHorizontalGroup(
            addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFlightLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(origin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yes)
                            .addComponent(no)))
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(9, 9, 9)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departTime, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(returnTime, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton4)
                        .addGap(135, 135, 135)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))
                        .addGap(11, 11, 11)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addFlightLayout.setVerticalGroup(
            addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFlightLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yes)
                    .addComponent(no)
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addFlightLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2))
                            .addGroup(addFlightLayout.createSequentialGroup()
                                .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addComponent(origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addFlightLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5))
                            .addGroup(addFlightLayout.createSequentialGroup()
                                .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(departTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10)
                .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(returnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel20))
                    .addGroup(addFlightLayout.createSequentialGroup()
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(addFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        main.add(addFlight, "card2");

        editRemoveFlight.setBackground(new java.awt.Color(36, 47, 65));
        editRemoveFlight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date1.setDateFormatString("yyyy-MM-dd");
        editRemoveFlight.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 180, 30));
        editRemoveFlight.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 180, 10));

        destination1.setBackground(new java.awt.Color(36, 47, 65));
        destination1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destination1.setForeground(new java.awt.Color(255, 255, 255));
        destination1.setBorder(null);
        editRemoveFlight.add(destination1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 180, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Airport_104px.png")); // NOI18N
        editRemoveFlight.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 109, 111));
        editRemoveFlight.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 180, 10));

        departTime1.setBackground(new java.awt.Color(36, 47, 65));
        departTime1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departTime1.setForeground(new java.awt.Color(255, 255, 255));
        departTime1.setBorder(null);
        editRemoveFlight.add(departTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 180, -1));

        jScrollPane4.setBackground(new java.awt.Color(204, 204, 204));

        flightEditDeleteTable.setBackground(new java.awt.Color(204, 204, 204));
        flightEditDeleteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Food", "Drink", "Cabin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        flightEditDeleteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightEditDeleteTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(flightEditDeleteTable);

        editRemoveFlight.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 538, 100));

        origin1.setBackground(new java.awt.Color(36, 47, 65));
        origin1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        origin1.setForeground(new java.awt.Color(255, 255, 255));
        origin1.setBorder(null);
        editRemoveFlight.add(origin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 180, -1));

        jLabel22.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("No of seats");
        editRemoveFlight.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        nos1.setBackground(new java.awt.Color(36, 47, 65));
        nos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nos1.setForeground(new java.awt.Color(255, 255, 255));
        nos1.setBorder(null);
        editRemoveFlight.add(nos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 180, -1));
        editRemoveFlight.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 180, 10));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Enter_32.png")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        editRemoveFlight.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        returnTime3.setBackground(new java.awt.Color(36, 47, 65));
        returnTime3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        returnTime3.setForeground(new java.awt.Color(255, 255, 255));
        returnTime3.setBorder(null);
        editRemoveFlight.add(returnTime3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 180, -1));

        jLabel23.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Flight Name");
        editRemoveFlight.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));
        editRemoveFlight.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 180, 10));

        jLabel24.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Price");
        editRemoveFlight.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));
        editRemoveFlight.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 180, 10));

        price1.setBackground(new java.awt.Color(36, 47, 65));
        price1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        price1.setForeground(new java.awt.Color(255, 255, 255));
        price1.setBorder(null);
        editRemoveFlight.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 180, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Flight");
        editRemoveFlight.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 43));

        jLabel26.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Return Time");
        editRemoveFlight.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Origin");
        editRemoveFlight.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        returnTime1.setBackground(new java.awt.Color(36, 47, 65));
        returnTime1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        returnTime1.setForeground(new java.awt.Color(255, 255, 255));
        returnTime1.setBorder(null);
        editRemoveFlight.add(returnTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 180, -1));
        editRemoveFlight.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 180, 10));

        jLabel28.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("Date");
        editRemoveFlight.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));
        editRemoveFlight.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 180, 10));

        jLabel29.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("Destination");
        editRemoveFlight.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));
        editRemoveFlight.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 180, 10));

        jLabel30.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("DepartTime");
        editRemoveFlight.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Trash_32.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        editRemoveFlight.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel31.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Edit or Delete");
        editRemoveFlight.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 43));

        fnameLB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fnameLB.setForeground(new java.awt.Color(255, 255, 255));
        editRemoveFlight.add(fnameLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 160, 20));

        main.add(editRemoveFlight, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //remove jpanel(s)
        main.removeAll();
        main.repaint();
        main.revalidate();

        //add jpanel
        main.add(addFlight);
        main.repaint();
        main.revalidate();
        tableLoad3(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = fname.getText();
        String orign = origin.getText();
        String dest = destination.getText();
        String fdate = ((JTextField)date.getDateEditor().getUiComponent()).getText();
        String dTime = departTime.getText();
        String rTime = returnTime.getText();
        int fnos = Integer.parseInt(nos.getText());
        double fprice = Double.parseDouble(price.getText());
        
        try{
            Date fTimeDB = new SimpleDateFormat("yyyy-MM-dd").parse(fdate);
            java.sql.Date sqlfTime = new java.sql.Date(fTimeDB.getTime());
            
            String q = "INSERT INTO flight (flightName,origin,destination,date,departTime,returnTime,noOfSeats,price) values (?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(q);
            
            pst.setString(1, name);
            pst.setString(2, orign);
            pst.setString(3, dest);
            pst.setDate(4, sqlfTime);
            pst.setString(5, dTime);
            pst.setString(6, rTime);
            pst.setInt(7, fnos);
            pst.setDouble(8, fprice);
            
            pst.execute();
            
            tableLoad3(1);
        }catch(SQLException | ParseException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void fnameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fnameCaretUpdate
        no.setVisible(false);
        jButton4.setEnabled(true);
        jLabel15.setText("Enter flight name");
        
        String flightname = fname.getText();
                
        if(!flightname.isEmpty()){
            String sql = "SELECT flightName FROM flight WHERE flightName like '"+flightname+"' ";
            try{
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                while(rs.next()){
                    if(flightname.equals(rs.getString("flightName"))){
                        no.setVisible(true);
                        yes.setVisible(false);
                        jLabel15.setText("Flight name already taken.");
                        jButton4.setEnabled(false);
                    }
                }
            }catch(SQLException e){
                System.out.println(e);
            }
        }
        
        for(int i=1;i<flightname.length();i++){
            if(Character.isWhitespace(flightname.charAt(i))){
                no.setVisible(true);
                jLabel15.setText("Do not use White spaces.");
                jButton4.setEnabled(false);
            }
        }
    }//GEN-LAST:event_fnameCaretUpdate

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //remove jpanel(s)
        main.removeAll();
        main.repaint();
        main.revalidate();

        //add jpanel
        main.add(editRemoveFlight);
        main.repaint();
        main.revalidate();
        tableLoad3(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update?");
        
        if (x==0){
            String flightName = fnameLB.getText();
            String forigin = origin1.getText();
            String fdestination = destination1.getText();
            String fdate = ((JTextField)date1.getDateEditor().getUiComponent()).getText();
            String dTime = departTime1.getText();
            String rTime = returnTime.getText();
            int fnos = Integer.parseInt(nos1.getText());
            double fprice = Double.parseDouble(price1.getText());
            
            String sql = "UPDATE flight SET flightName = ?, origin = ?,destination = ?,date = ?,departTime = ?,returnTime = ?,noOfSeats = ?,price = ? WHERE flightName like '"+flightName+"'";
            
            try{
                Date fTimeDB = new SimpleDateFormat("yyyy-MM-dd").parse(fdate);
                java.sql.Date sqlfTime = new java.sql.Date(fTimeDB.getTime());
                pst = con.prepareStatement(sql);
                pst.setString(1, flightName);
                pst.setString(2, forigin);
                pst.setString(3, fdestination);
                pst.setDate(4, sqlfTime);
                pst.setString(5, dTime);
                pst.setString(6, rTime);
                pst.setInt(7, fnos);
                pst.setDouble(8, fprice);
                pst.execute();
                
                //load table
                tableLoad3(2);
            }catch(SQLException e){
                System.out.println(e);
            } catch (ParseException ex) {
                Logger.getLogger(flightHandler.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete?");

        if (x==0){
            String fname3 = fnameLB.getText();
            String sql = "DELETE from flight where flightName like '"+fname3+"'";
            try{
                pst = con.prepareStatement(sql);
                pst.execute();

                //load table
                tableLoad3(2);
            }catch(SQLException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void flightEditDeleteTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightEditDeleteTableMouseClicked
        int r = flightEditDeleteTable.getSelectedRow();
        
        String name = flightEditDeleteTable.getValueAt(r, 0).toString();
        String forign = flightEditDeleteTable.getValueAt(r, 1).toString();
        String fdest = flightEditDeleteTable.getValueAt(r, 2).toString();
        String fdate = flightEditDeleteTable.getValueAt(r, 3).toString();
        String dTime = flightEditDeleteTable.getValueAt(r, 4).toString();
        String rTime = flightEditDeleteTable.getValueAt(r, 5).toString();
        String fnos = flightEditDeleteTable.getValueAt(r, 6).toString();
        String fprice = flightEditDeleteTable.getValueAt(r, 7).toString();
        
        fnameLB.setText(name);
        origin1.setText(forign);
        destination1.setText(fdest);
        date.setDateFormatString(fdate);
        departTime1.setText(dTime);
        returnTime1.setText(rTime);
        nos1.setText(fnos);
        price1.setText(fprice);
    }//GEN-LAST:event_flightEditDeleteTableMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to Log out?");
        if (x==0){
            Login l1 = new Login();
            l1.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flightHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flightHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flightHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flightHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flightHandler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addFlight;
    private com.toedter.calendar.JDateChooser date;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JTextField departTime;
    private javax.swing.JTextField departTime1;
    private javax.swing.JTextField destination;
    private javax.swing.JTextField destination1;
    private javax.swing.JPanel editRemoveFlight;
    private javax.swing.JTable flightAddTable;
    private javax.swing.JTable flightEditDeleteTable;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel fnameLB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JPanel main;
    private javax.swing.JLabel no;
    private javax.swing.JTextField nos;
    private javax.swing.JTextField nos1;
    private javax.swing.JTextField origin;
    private javax.swing.JTextField origin1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField returnTime;
    private javax.swing.JTextField returnTime1;
    private javax.swing.JTextField returnTime2;
    private javax.swing.JTextField returnTime3;
    private javax.swing.JLabel yes;
    // End of variables declaration//GEN-END:variables
}
