/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.dbconnect;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Madhawa
 */
public final class ticketHandler extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    PreparedStatement pst1 = null;
    ResultSet rs1 = null;
    
    /**
     * Creates new form ticketHandler
     */
    public ticketHandler() {
        initComponents();
        
        //set the location of the jframe to the center of the screen
        this.pack();
        this.setLocationRelativeTo(null);
        
        //connecting to DB
        con = dbconnect.connect();
        
        //load table
        tableLoad(1);
        
    }
    
    public void tableLoad(int a){
        try{
            String q2 = "SELECT packageID,name,priceRatio,food,drink,cabin FROM package";
            pst = con.prepareStatement(q2);
            rs = pst.executeQuery();
            
            if(a==1){
                packageAddTable.setModel(DbUtils.resultSetToTableModel(rs));
            }else if(a==2){
                packageEditDeleteTable.setModel(DbUtils.resultSetToTableModel(rs));
            }
            
        }catch(SQLException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        containerJP = new javax.swing.JPanel();
        menuBarJP = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        mainJP = new javax.swing.JPanel();
        addJP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        foodBox = new javax.swing.JTextField();
        drinkBox = new javax.swing.JTextField();
        cabinBox = new javax.swing.JTextField();
        priceBox = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        packageAddTable = new javax.swing.JTable();
        editJP = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        priceBox1 = new javax.swing.JTextField();
        foodBox1 = new javax.swing.JTextField();
        drinkBox1 = new javax.swing.JTextField();
        nameBox1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        packageEditDeleteTable = new javax.swing.JTable();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        cabinBox1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        idLable = new javax.swing.JLabel();
        ticketJP = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        to = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        dTime = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        aTime = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        totalSeats = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        seatsLeft = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Add Property_96px.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        containerJP.setBackground(new java.awt.Color(36, 47, 65));

        menuBarJP.setBackground(new java.awt.Color(0, 153, 153));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Add_32.png")); // NOI18N
        jButton1.setAutoscrolls(true);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Edit_32.png")); // NOI18N
        jButton2.setAutoscrolls(true);
        jButton2.setBorderPainted(false);
        jButton2.setDefaultCapable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Ticket_32.png")); // NOI18N
        jButton7.setAutoscrolls(true);
        jButton7.setBorderPainted(false);
        jButton7.setDefaultCapable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Logout_Rounded_Left_32.png")); // NOI18N
        jButton8.setAutoscrolls(true);
        jButton8.setBorderPainted(false);
        jButton8.setDefaultCapable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarJPLayout = new javax.swing.GroupLayout(menuBarJP);
        menuBarJP.setLayout(menuBarJPLayout);
        menuBarJPLayout.setHorizontalGroup(
            menuBarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuBarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuBarJPLayout.setVerticalGroup(
            menuBarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarJPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainJP.setBackground(new java.awt.Color(153, 255, 255));
        mainJP.setLayout(new java.awt.CardLayout());

        addJP.setBackground(new java.awt.Color(36, 47, 65));
        addJP.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Price");

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Drinks");

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Foods");

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Cabin Type");

        nameBox.setBackground(new java.awt.Color(36, 47, 65));
        nameBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameBox.setForeground(new java.awt.Color(255, 255, 255));
        nameBox.setBorder(null);
        nameBox.setCaretColor(new java.awt.Color(255, 255, 255));

        foodBox.setBackground(new java.awt.Color(36, 47, 65));
        foodBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        foodBox.setForeground(new java.awt.Color(255, 255, 255));
        foodBox.setBorder(null);

        drinkBox.setBackground(new java.awt.Color(36, 47, 65));
        drinkBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        drinkBox.setForeground(new java.awt.Color(255, 255, 255));
        drinkBox.setBorder(null);

        cabinBox.setBackground(new java.awt.Color(36, 47, 65));
        cabinBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cabinBox.setForeground(new java.awt.Color(255, 255, 255));
        cabinBox.setBorder(null);

        priceBox.setBackground(new java.awt.Color(36, 47, 65));
        priceBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceBox.setForeground(new java.awt.Color(255, 255, 255));
        priceBox.setBorder(null);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Enter_32.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Add a new package");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Add Property_96px.png")); // NOI18N

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));

        packageAddTable.setBackground(new java.awt.Color(204, 204, 204));
        packageAddTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Food", "Drink", "Cabin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        packageAddTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packageAddTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(packageAddTable);

        javax.swing.GroupLayout addJPLayout = new javax.swing.GroupLayout(addJP);
        addJP.setLayout(addJPLayout);
        addJPLayout.setHorizontalGroup(
            addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJPLayout.createSequentialGroup()
                .addGroup(addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel6))
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addJPLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel7))))
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drinkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cabinBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addComponent(jButton4))
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addJPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        addJPLayout.setVerticalGroup(
            addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJPLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(priceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(foodBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel7)))
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(addJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5))
                    .addGroup(addJPLayout.createSequentialGroup()
                        .addComponent(drinkBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cabinBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        mainJP.add(addJP, "card3");

        editJP.setBackground(new java.awt.Color(36, 47, 65));

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("ID");

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Name");

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Foods");

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Price");

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Drinks");

        priceBox1.setBackground(new java.awt.Color(36, 47, 65));
        priceBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceBox1.setForeground(new java.awt.Color(255, 255, 255));
        priceBox1.setBorder(null);

        foodBox1.setBackground(new java.awt.Color(36, 47, 65));
        foodBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        foodBox1.setForeground(new java.awt.Color(255, 255, 255));
        foodBox1.setBorder(null);

        drinkBox1.setBackground(new java.awt.Color(36, 47, 65));
        drinkBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        drinkBox1.setForeground(new java.awt.Color(255, 255, 255));
        drinkBox1.setBorder(null);

        nameBox1.setBackground(new java.awt.Color(36, 47, 65));
        nameBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameBox1.setForeground(new java.awt.Color(255, 255, 255));
        nameBox1.setBorder(null);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Enter_32.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("       Edit or delete a package");

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 204));

        packageEditDeleteTable.setBackground(new java.awt.Color(204, 204, 204));
        packageEditDeleteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Price", "Food", "Drink", "Cabin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        packageEditDeleteTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packageEditDeleteTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(packageEditDeleteTable);

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Cabin Type");

        cabinBox1.setBackground(new java.awt.Color(36, 47, 65));
        cabinBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cabinBox1.setForeground(new java.awt.Color(255, 255, 255));
        cabinBox1.setBorder(null);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Trash_32.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Edit Property_96px.png")); // NOI18N

        idLable.setForeground(new java.awt.Color(255, 255, 255));
        idLable.setText("00");

        javax.swing.GroupLayout editJPLayout = new javax.swing.GroupLayout(editJP);
        editJP.setLayout(editJPLayout);
        editJPLayout.setHorizontalGroup(
            editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editJPLayout.createSequentialGroup()
                .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editJPLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editJPLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editJPLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(editJPLayout.createSequentialGroup()
                                        .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12))
                                        .addGap(43, 43, 43)
                                        .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(priceBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idLable)))
                                    .addGroup(editJPLayout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(editJPLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(12, 12, 12)
                                                .addComponent(cabinBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(editJPLayout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(editJPLayout.createSequentialGroup()
                                        .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(foodBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(drinkBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editJPLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel15))
                                    .addGroup(editJPLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jButton5)
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton6)
                                        .addGap(0, 27, Short.MAX_VALUE)))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        editJPLayout.setVerticalGroup(
            editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editJPLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editJPLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editJPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editJPLayout.createSequentialGroup()
                                .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editJPLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel10)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel12))
                                    .addGroup(editJPLayout.createSequentialGroup()
                                        .addComponent(idLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(nameBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(priceBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editJPLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editJPLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(20, 20, 20)
                                        .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(drinkBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(editJPLayout.createSequentialGroup()
                                        .addComponent(foodBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(cabinBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editJPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6)
                                    .addComponent(jButton5))
                                .addGap(11, 11, 11)))
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        mainJP.add(editJP, "card3");

        ticketJP.setBackground(new java.awt.Color(36, 47, 65));

        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(ticketTable);

        jLabel19.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Flight");

        from.setForeground(new java.awt.Color(255, 255, 255));
        from.setText("00");

        jLabel21.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("From");

        to.setForeground(new java.awt.Color(255, 255, 255));
        to.setText("00");

        jLabel22.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("To");

        dTime.setForeground(new java.awt.Color(255, 255, 255));
        dTime.setText("00");

        jLabel23.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Depature Time");

        aTime.setForeground(new java.awt.Color(255, 255, 255));
        aTime.setText("00");

        jLabel24.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Arrive Time");

        totalSeats.setForeground(new java.awt.Color(255, 255, 255));
        totalSeats.setText("00");

        jLabel25.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Total Seats");

        seatsLeft.setForeground(new java.awt.Color(255, 255, 255));
        seatsLeft.setText("00");

        jLabel26.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Seats Left");

        jLabel27.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("           Ticket Details");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Madhawa\\Documents\\NetBeansProjects\\icons\\Search_Property_16.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ticketJPLayout = new javax.swing.GroupLayout(ticketJP);
        ticketJP.setLayout(ticketJPLayout);
        ticketJPLayout.setHorizontalGroup(
            ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketJPLayout.createSequentialGroup()
                .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketJPLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel27))
                    .addGroup(ticketJPLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ticketJPLayout.createSequentialGroup()
                                .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ticketJPLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel21)
                                        .addGap(27, 27, 27)
                                        .addComponent(from))
                                    .addGroup(ticketJPLayout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ticketJPLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(29, 29, 29)
                                        .addComponent(dTime))
                                    .addGroup(ticketJPLayout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ticketJPLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel25)
                                        .addGap(23, 23, 23)
                                        .addComponent(totalSeats))
                                    .addGroup(ticketJPLayout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ticketJPLayout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel22))
                                    .addGroup(ticketJPLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel24))
                                    .addGroup(ticketJPLayout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel26)))
                                .addGap(25, 25, 25)
                                .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(to)
                                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aTime)
                                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatsLeft)
                                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ticketJPLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel19)
                        .addGap(16, 16, 16)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jButton3)))
                .addGap(26, 26, 26))
        );
        ticketJPLayout.setVerticalGroup(
            ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketJPLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ticketJPLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ticketJPLayout.createSequentialGroup()
                        .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(from)
                            .addComponent(to))
                        .addGap(2, 2, 2)
                        .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(dTime)
                            .addComponent(aTime))
                        .addGap(2, 2, 2)
                        .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(totalSeats)
                            .addComponent(seatsLeft))
                        .addGap(2, 2, 2)
                        .addGroup(ticketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ticketJPLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel22)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel24)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel26)))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mainJP.add(ticketJP, "card3");

        javax.swing.GroupLayout containerJPLayout = new javax.swing.GroupLayout(containerJP);
        containerJP.setLayout(containerJPLayout);
        containerJPLayout.setHorizontalGroup(
            containerJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerJPLayout.createSequentialGroup()
                .addComponent(menuBarJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerJPLayout.setVerticalGroup(
            containerJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerJPLayout.createSequentialGroup()
                .addGroup(containerJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuBarJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerJP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //remove jpanel(s)
        mainJP.removeAll();
        mainJP.repaint();
        mainJP.revalidate();
        
        //add jpanel
        mainJP.add(addJP);
        mainJP.repaint();
        mainJP.revalidate();
        tableLoad(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //remove jpanel(s)
        mainJP.removeAll();
        mainJP.repaint();
        mainJP.revalidate();
        
        //add jpanel
        mainJP.add(editJP);
        mainJP.repaint();
        mainJP.revalidate();
        tableLoad(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = nameBox.getText();
        String price = priceBox.getText();
        String food = foodBox.getText();
        String drink = drinkBox.getText();
        String cabin = cabinBox.getText();
        
        try{
            String q = "INSERT INTO package (name,priceRatio,food,drink,cabin) values ('"+ name +"', '"+ price +"', '"+ food +"', '"+ drink +"', '"+ cabin +"')";
            pst = con.prepareStatement(q);
            pst.execute();
            tableLoad(1);
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update?");
        
        if (x==0){
            String id = idLable.getText();
            String name = nameBox1.getText();
            String price = priceBox1.getText();
            String food = foodBox1.getText();
            String drink = drinkBox1.getText();
            String cabin = cabinBox1.getText();
            String sql = "UPDATE package SET name = '"+ name +"', priceRatio = '"+ price +"',food = '"+ food +"',drink = '"+ drink +"',cabin = '"+ cabin +"' WHERE packageID = '"+ id +"'";
            
            try{
                pst = con.prepareStatement(sql);
                pst.execute();
                
                //load table
                tableLoad(2);
            }catch(SQLException e){
                System.out.println(e);
            }
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete?");
        
        if (x==0){
            String id = idLable.getText();
            String sql = "DELETE from package where packageID = '"+ id +"'";
            try{
                pst = con.prepareStatement(sql);
                pst.execute();
                
                //load table
                tableLoad(2);
            }catch(SQLException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void packageEditDeleteTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packageEditDeleteTableMouseClicked
        int r = packageEditDeleteTable.getSelectedRow();
        
        String id = packageEditDeleteTable.getValueAt(r, 0).toString();
        String name = packageEditDeleteTable.getValueAt(r, 1).toString();
        String price = packageEditDeleteTable.getValueAt(r, 2).toString();
        String food = packageEditDeleteTable.getValueAt(r, 3).toString();
        String drink = packageEditDeleteTable.getValueAt(r, 4).toString();
        String cabin = packageEditDeleteTable.getValueAt(r, 5).toString();
        
        idLable.setText(id);
        nameBox1.setText(name);
        priceBox1.setText(price);
        foodBox1.setText(food);
        drinkBox1.setText(drink);
        cabinBox1.setText(cabin);
    }//GEN-LAST:event_packageEditDeleteTableMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //remove jpanel(s)
        mainJP.removeAll();
        mainJP.repaint();
        mainJP.revalidate();
        
        //add jpanel
        mainJP.add(ticketJP);
        mainJP.repaint();
        mainJP.revalidate();
        
        jComboBox2.removeAllItems();
        String q = "SELECT flightName FROM flight";
        try {
            pst = con.prepareStatement(q);
            rs = pst.executeQuery(q);
            while(rs.next()){
                jComboBox2.addItem(rs.getString("flightName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ticketHandler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String fname = jComboBox2.getSelectedItem().toString();
        System.out.println(fname);
        String sql = "SELECT * FROM flight WHERE flightName like '"+fname+"'";
        try{
            pst1 = con.prepareStatement(sql);
            rs1 = pst1.executeQuery();
            while(rs1.next()){
                from.setText(rs1.getString("origin"));
                to.setText(rs1.getString("destination"));
                dTime.setText(rs1.getString("departTime"));
                aTime.setText(rs1.getString("returnTime"));
                totalSeats.setText(rs1.getString("noOfSeats"));
                }
            
            //getting all the booked tickets of the selected flight
            String sql1 = "SELECT * FROM ticket WHERE departFlight like '"+fname+"' OR returnFlight like '"+fname+"'"; 
            pst = con.prepareStatement(sql1);
            rs = pst.executeQuery();
            ticketTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            //calculating the no of seats left using total seats and no of rows of the table and assigning to the label
            seatsLeft.setText(String.valueOf(Integer.parseInt(totalSeats.getText()) - ticketTable.getRowCount()));
        }catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to Log out?");
        if (x==0){
            Login l1 = new Login();
            l1.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void packageAddTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packageAddTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_packageAddTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ticketHandler().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aTime;
    private javax.swing.JPanel addJP;
    private javax.swing.JTextField cabinBox;
    private javax.swing.JTextField cabinBox1;
    private javax.swing.JPanel containerJP;
    private javax.swing.JLabel dTime;
    private javax.swing.JTextField drinkBox;
    private javax.swing.JTextField drinkBox1;
    private javax.swing.JPanel editJP;
    private javax.swing.JTextField foodBox;
    private javax.swing.JTextField foodBox1;
    private javax.swing.JLabel from;
    private javax.swing.JLabel idLable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainJP;
    private javax.swing.JPanel menuBarJP;
    private javax.swing.JTextField nameBox;
    private javax.swing.JTextField nameBox1;
    private javax.swing.JTable packageAddTable;
    private javax.swing.JTable packageEditDeleteTable;
    private javax.swing.JTextField priceBox;
    private javax.swing.JTextField priceBox1;
    private javax.swing.JLabel seatsLeft;
    private javax.swing.JPanel ticketJP;
    private javax.swing.JTable ticketTable;
    private javax.swing.JLabel to;
    private javax.swing.JLabel totalSeats;
    // End of variables declaration//GEN-END:variables
}
